// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgbakhoviazvpuyjojxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnYmFraG92aWF6dnB1eWpvanh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Mzc5ODQsImV4cCI6MjA1ODAxMzk4NH0.d1BTdvuk0X9ZBxJnf4_s4JKmhoG9ClsGgJA-ihUwTkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);